cms/urls.py
from django.urls import path

from . import views

app_name = 'cms'
#これはurlを定義するためのやつ
urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('post/', views.Post.as_view(), name='post'),
    #path('user/<int:pk>/post/', views.UserPost.as_view(), name='user_post'),
    path('user/<int:pk>/post/', views.UserPostView.as_view(), name='user_post'),
    path('user/<int:pk>/update/', views.UserUpdate.as_view(), name='user_update'),
    path('user/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user/', views.UserList.as_view(), name='user_list'),
    path('user/<int:pk>/delete/', views.UserDelete.as_view(), name='user_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cms.urls')),
]

cms/models.py
#from django.db import models

# Create your models here.
from django.contrib.auth.base_user import (
    AbstractBaseUser, BaseUserManager,
)
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model


# User-related
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class AbstractUser(AbstractBaseUser, PermissionsMixin):

    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    email = models.EmailField(_('email address'), unique=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    twitter = models.CharField(_('Twitter'), max_length=50, blank=True)
    no_one = models.CharField(_('no_one'), max_length=280, blank=True)
    no_two = models.CharField(_('no_two'), max_length=280, blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        abstract = True

    def __str__(self):
        return self.email

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class User(AbstractUser):
    class Meta(AbstractUser.Meta):
        swappable = "AUTH_USER_MODEL"

class PostModel(models.Model):
    no_one = models.CharField(max_length=280, blank=True)
    no_two = models.CharField(max_length=280, blank=True)

class UserPostModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    no_one = models.CharField(_('no_one'), max_length=280, blank=True)
    no_two = models.CharField(_('no_one'), max_length=280, blank=True)

cms/forms.py
#これは情報を共有するためのやつ
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from .models import UserPostModel
UserModel = get_user_model()


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       self.fields['username'].widget.attrs['class'] = 'input'
       self.fields['password'].widget.attrs['class'] = 'input'

class UserCreateForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ('username', 'first_name', 'last_name', 'email', 'twitter')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'

class UserPostForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ('no_one', 'no_two')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'

class UserPostForm(forms.ModelForm) :
   class Meta :
       model = UserPostModel
       fields=("no_one","no_two")

   def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       for field in self.fields.values():
           field.widget.attrs['class'] = 'input'

cms/views.py
from pyexpat import model
from django.contrib.auth import get_user_model, login
from django.contrib.auth.views import (
    LoginView, LogoutView,
)
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from .mixins import OnlyYouMixin
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm,UserPostForm
)
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView, UpdateView, DeleteView,
)
from django.views.generic import ListView, CreateView, FormView
from .models import PostModel,UserPostModel
from model.score import ScoreGenerator

UserModel = get_user_model()
class UserCreate(CreateView):
    form_class = UserCreateForm
    template_name = 'cms/signup.html'
    success_url = reverse_lazy('cms:top')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        return HttpResponseRedirect(self.get_success_url())

class TopView(TemplateView):
    template_name = 'cms/top.html'

class Logout(LogoutView):
    pass

class Login(LoginView):
    form_class = LoginForm
    template_name = 'cms/login.html'

class UserUpdate(OnlyYouMixin, UpdateView):
    model = UserModel
    form_class = UserUpdateForm
    template_name = 'cms/user_update.html'

    def get_success_url(self):
        return resolve_url('cms:user_detail', pk=self.kwargs['pk'])

class UserDetail(DetailView):
    model = UserModel
    template_name = 'cms/user_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context

class UserList(ListView):
    model = UserModel
    template_name = 'cms/user_list.html'

class UserDelete(OnlyYouMixin, DeleteView):
    model = UserModel
    template_name = 'cms/user_delete.html'
    success_url = reverse_lazy('cms:top')

class Post(CreateView):
    model = PostModel
    template_name = 'cms/post.html'
    fields = ('no_one', 'no_two')
    success_url = reverse_lazy('cms:top')

    def post(self, request, *args, **kwargs):
        #スコアパラメータの計算
        score_one = ScoreGenerator(request.POST['no_one']).calculate_score()
        score_two = ScoreGenerator(request.POST['no_two']).calculate_score()
        score_values = []

        #2つの文章のスコアを計算し，平均をとる
        for one, two in zip(score_one.values(), score_two.values()):
            score = (one + two) / 2
            score_values.append(score)

        params = {}
        labels = ['negative', 'mount', 'ill']
        for label, value in zip(labels, score_values):
            params[label] = value

        return render(request, 'cms/result.html', params)

class UserPost(OnlyYouMixin, UpdateView):
    model = UserModel
    form_class = UserPostForm
    template_name = 'cms/user_post.html'

    def get_success_url(self):
        return resolve_url('cms:user_detail', pk=self.kwargs['pk'])

    def post(self, request, *args, **kwargs):
        #スコアパラメータの計算
        score_one = ScoreGenerator(request.POST['no_one']).calculate_score()
        score_two = ScoreGenerator(request.POST['no_two']).calculate_score()
        score_values = []

        #2つの文章のスコアを計算し，平均をとる
        for one, two in zip(score_one.values(), score_two.values()):
            score = (one + two) / 2
            score_values.append(score)

        params = {}
        labels = ['negative', 'mount', 'ill']
        for label, value in zip(labels, score_values):
            params[label] = value

        return render(request, 'cms/result.html', params)


class UserPostView(OnlyYouMixin,CreateView):
    model = UserPostModel
    template_name = 'cms/user_post.html'
    fields = ('no_one', 'no_two')
    success_url = reverse_lazy('cms:top')

    def post(self, request, *args, **kwargs):
        #スコアパラメータの計算
        score_one = ScoreGenerator(request.POST['no_one']).calculate_score()
        score_two = ScoreGenerator(request.POST['no_two']).calculate_score()
        score_values = []

        #2つの文章のスコアを計算し，平均をとる
        for one, two in zip(score_one.values(), score_two.values()):
            score = (one + two) / 2
            score_values.append(score)

        params = {}
        labels = ['negative', 'mount', 'ill']
        for label, value in zip(labels, score_values):
            params[label] = value

        return render(request, 'cms/result.html', params)

cms/templates/cms/base.html
<!-- これは共通因子をまとめるためのhtmlファイル -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}Django Sprint</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>
    <!-- NAVIGATION BAR -->
    <header>
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <!-- LOGO -->
                <a class="navbar-item" href="/">
                    <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
                </a>
                <!-- HAMBURGER MENU -->
                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="my-menu">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            <div class="navbar-end">
                {% if user.is_authenticated %}
                <a class="navbar-item" href="{% url 'cms:logout' %}">Log out</a>
                {% else %}
                <a class="navbar-item is-grey" href="#">About</a>
                <div class="buttons">
                <a class="button is-info navbar-item" href="{% url 'cms:signup' %}"><strong>Sign up</strong></a>
                <a class="button is-light navbar-item" href="{% url 'cms:login' %}"><strong>Log in</strong></a>
                </div>
                {% endif %}
            </div>
        </nav>
    </header>
    <!-- MESSAGE -->
    {% for field, errors in form.errors.items %}
    <article class="message is-warning">
        <div class="message-body">
        {% for error in errors %}
            <p><strong>{{ error }}</strong></p>
        {% endfor %}
        </div>
    </article>
    {% endfor %}
    <!-- MAIN -->
    <main>
        {% block hero %}{% endblock %}
        {% block tab %}{% endblock %}
        {% block content %}{% endblock %}
    </main>
    <!-- FOOTER -->
    <footer class="footer">
        <div class="container">
            <div class="content has-text-centered">
                嫌いなツイートから性格診断しよう！
            </div>
            <div class="content has-text-centered">
                <a href="#" class="has-text-dark">About</a> |
                <a href="#" class="has-text-dark">Contact</a> |
                <a href="#" class="has-text-danger">Report an issue</a>
            </div>
        </div>
    </footer>

    <!-- FOR JAVASCRIPT -->
    <script>
        <!-- FOR HAMBURGER MENU -->
        for (const burder of document.getElementsByClassName('navbar-burger')) {
            const menuId = burder.dataset.target;
            const menu = document.getElementById(menuId);
            burder.addEventListener('click', e => {
                burder.classList.toggle('is-active');
                menu.classList.toggle('is-active');
            });
        }
        {% block extrajs %}{% endblock %}
    </script>

</body>
</html>

cms/templates/cms/login.html
{% extends 'cms/base.html' %}

{% block title %}Login | {% endblock %}

{% block content %}
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">ログイン</h1>
        <h2 class="subtitle is-6">Login</h2>
        <hr>
        <p class="help">アカウントをお持ちでない方へ：サインアップは<a href="{% url 'cms:signup' %}">こちら</a></p>
        <br>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <label class="label">ユーザーネーム</label>
                <div class="control has-icons-left">
                    {{ form.username }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">パスワード</label>
                <div class="control has-icons-left">
                    {{ form.password }}
                    <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                </div>
            </div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="ログイン" class="button is-success">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>
        </form>
    </div>
</section>
{% endblock %}

cms/templates/cms/post.html
{% extends 'cms/base.html' %}

{% block title %}Login | {% endblock %}

{% block content %}
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">嫌いなツイートの投稿</h1>
        <hr>
        <form method="post">
            {% csrf_token %}
            <div class="field">
                <label class="label">その1</label>
                <input class="input" type="text" name="no_one" placeholder="むかつくツイートを入力してください！">
            </div>
            <div class="field">
                <label class="label">その2</label>
                <input class="input" type="text" name="no_two" placeholder="むかつくツイートを入力してください！">
            </div>
            <div class="field">
            <div class="navbar-top">
            <p class="control">
            <a class="bd-tw-button button" data-social-network="Twitter" data-social-action="tweet" data-social-target="https://bulma.io" target="_blank" href="https://twitter.com/">
              <span class="icon">
                <i class="fab fa-twitter"></i>
              </span>
              <span>
                嫌いなツイートを探す
              </span>
            </a>
            </p></div></div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="診断" class="button is-success">
                    <input type="hidden" name="next" value="{{next}}" >
                </p>
            </div>

        </form>
    </div>
</section>
{% endblock %}

cms/templates/cms/result.html
{% extends 'cms/base.html' %}

{% block title %}Result | {% endblock %}

{% load static %}

{% block content %}
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">診断結果</h1>
        <hr>
        <div class="field">
            <div class="box">
                <div style="position:relative; width:500px; height:500px;">
                    <canvas id="chart" width="400px" height="600px"></canvas>
                    <!-- スコアチャートを表示するためのスクリプト-->
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.1/chart.js"></script>
                    <script>
                      var nega_score  = JSON.parse("{{negative | safe}}");
                      var mount_score = JSON.parse("{{mount | safe}}");
                      var ill_score   = JSON.parse("{{ill | safe}}");
                    </script>
                    <script src="{% static 'cms/display.js' %}"></script>
                </div>
            </div>
        </div>
        <div class="field">
        <p class="control">
            <input type="button" onclick="history.back()" value="もう一度診断する" class="button is-success">
        </p>
        </div>
    </div>
</section>
{% endblock %}

cms/templates/cms/signup.html
{% extends 'cms/base.html' %}

{% block title %}Signup | {% endblock %}

{% block content %}
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">サインアップ</h1>
        <h2 class="subtitle is-6">Sign up</h2>
        <hr>
        <p class="help">アカウントをお持ちの方へ：ログインは<a href="{% url 'cms:login' %}">こちら</a></p>
        <br>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <label class="label">ユーザーネーム</label>
                <div class="control has-icons-left">
                    {{ form.username }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">メールアドレス</label>
                <div class="control has-icons-left">
                    {{ form.email }}
                    <span class="icon is-small is-left"><i class="fas fa-envelope"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">パスワード</label>
                <div class="control has-icons-left">
                    {{ form.password1 }}
                    <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">パスワード（確認）</label>
                <div class="control has-icons-left">
                    {{ form.password2 }}
                    <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                </div>
            </div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="登録" class="button is-success">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>
        </form>
    </div>
</section>
{% endblock %}

cms/templates/cms/top.html
{% extends 'cms/base.html' %}

{% block title %}Home | {% endblock %}

{% block hero %}
<section class="hero is-medium is-info is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">むかつくツイートから性格を診断しよう！</h1>
            <!--<h2 class="subtitle">Subtitle</h2>-->
            <a href="#">
                <button class="button is-info is-inverted is-outlined">
                    <strong>More Info</strong>
                </button>
            </a>
            {% if user.is_authenticated %}
            <a class="button is-info is-inverted is-outlined" href="{% url 'cms:user_post' user.id %}">
                <strong>診断開始!</strong>
            </a>
            {% else %}
            <a class="button is-info is-inverted is-outlined" href="{% url 'cms:post' %}">
                <strong>診断開始!</strong>
            </a>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="section is-medium">
    <div class="container">
        <div class="has-text-centered">
            <h1 class="title">Section</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        </div>
    </div>
</section>
{% endblock %}

cms/templates/cms/user_delete.html
{% extends 'cms/base.html' %}

{% block title %}{{ user.username }} | {% endblock %}

{% block content %}
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">ユーザー情報の削除</h1>
        <h2 class="subtitle is-6">Delete your information</h2>
        <hr>
        <p><strong class="has-text-danger">本当にユーザー情報を削除してよろしいですか？</strong></p>
        <br>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <p class="control">
                    <input type="submit" value="確認して削除" class="button is-danger">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>
        </form>
    </div>
</section>
{% endblock %}

cms/templates/cms/user_detail.html
{% extends 'cms/base.html' %}

{% block title %}{{ user.last_name }} {{ user.first_name }} | {% endblock %}

{% block hero %}
<section class="hero is-link is-bold">
    <div class="hero-body">
        <div class="container">
            <div class="media">
                <div class="media-left">
                    <figure class="image is-64x64 is-left">
                        <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png">
                    </figure>
                </div>
                <div class="media-content">
                    <h1 class="title">
                        {{ user.last_name }} {{ user.first_name }}
                    </h1>
                    <h2 class="subtitle">
                        {{ user.username }}
                    </h2>
                    {% if user.pk == request.user.pk %}
                    <a href="{% url 'cms:user_update' user.pk %}">
                        <button class="button is-small is-info is-inverted is-outlined">
                            <span class="icon is-small is-left"><i class="fas fa-user-edit"></i></span>
                            <strong>プロフィールを追加する</strong>
                        </button>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

...
{% block content %}
<section class="section">
    <div class="container">
        <div class="level">
            <div class="level-left">
                {% if user.twitter %}
                <div class="level-item">
                    <div class="tags has-addons">
                        <span class="tag"><span class="icon is-small is-left"><i class="fab fa-twitter"></i></span></span>
                        <span class="tag is-dark"><a class="has-text-white" href="https://twitter.com/{{ user.twitter }}" target="_blank">@{{ user.twitter }}</a></span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.</p>
    </div>
</section>
{% endblock %}

cms/templates/cms/user_list.html
{% extends 'cms/base.html' %}

{% block title %}ユーザー一覧 | {% endblock %}

{% block hero %}
<section class="hero is-small is-link is-bold">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h1 class="title">ユーザー一覧</h1>
            <h2 class="subtitle">User List</h2>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="tile is-ancestor">
            <div class="tile is-12 is-vertical is-parent">
                {% for object in object_list %}
                <div class="tile is-child box">
                    <a class="title is-4" href="{% url 'cms:user_detail' object.id %}">{{ object.username }}</a>
                    <p>Lorem ipsum dolor sit</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

cms/templates/cms/user_post.html
{% extends 'cms/base.html' %}

{% block title %}Login | {% endblock %}

{% block content %}
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">嫌いなツイートの投稿</h1>
        <hr>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <label class="label">その1</label>
                <input class="input" type="text" name="no_one" placeholder="むかつくツイートを入力してください！">
            </div>
            <div class="field">
                <label class="label">その2</label>
                 <input class="input" type="text" name="no_two" placeholder="むかつくツイートを入力してください！">
            </div>
            <div class="field">
            <div class="navbar-top">
            <p class="control">
            <a class="bd-tw-button button" data-social-network="Twitter" data-social-action="tweet" data-social-target="https://bulma.io" target="_blank" href="https://twitter.com/">
              <span class="icon">
                <i class="fab fa-twitter"></i>
              </span>
              <span>
                嫌いなツイートを探す
              </span>
            </a>
            </p></div></div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="診断" class="button is-success">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>

        </form>
    </div>
</section>
{% endblock %}

cms/templates/cms/user_update.html
{% extends 'cms/base.html' %}

{% block title %}{{ user.username }} | {% endblock %}

{% block content %}
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">ユーザー情報の更新</h1>
        <h2 class="subtitle is-6">Update your information</h2>
        <hr>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <label class="label">ユーザーネーム</label>
                <div class="control has-icons-left">
                    {{ form.username }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">姓</label>
                <div class="control has-icons-left">
                    {{ form.last_name }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">名</label>
                <div class="control has-icons-left">
                    {{ form.first_name }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">メールアドレス</label>
                <div class="control has-icons-left">
                    {{ form.email }}
                    <span class="icon is-small is-left"><i class="fas fa-envelope"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">Twitter</label>
                <div class="control has-icons-left">
                {{ form.twitter }}
                <span class="icon is-small is-left"><i class="fab fa-twitter"></i></span>
                </div>
            </div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="保存" class="button is-success">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>
        </form>
        <hr>
        <a href="{% url 'cms:user_delete' user.pk %}">
            <button class="button is-danger is-outlined">削除</button>
        </a>
    </div>
</section>
{% endblock %}